name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@197470359c0e1dee90ae8308a8cdaec4ab5a8785 # main

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Lint
        run: bun run check:eslint

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage
